version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    steps:
      - checkout
      - run: find .
      - run: dotnet restore src/GlobalX.Hypermedia.AspNetCore.sln
      - run: dotnet build src/GlobalX.Hypermedia.AspNetCore.sln
  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    steps:
      - checkout
      - run: find .
      - run: dotnet restore src/GlobalX.Hypermedia.AspNetCore.sln
      - run: dotnet pack src/GlobalX.Hypermedia.AspNetCore.sln --include-source --include-symbols -o ../../nuget
      - run: dotnet nuget push ./nuget/GlobalX.Hypermedia.AspNetCore*.nupkg -k "$NUGET_KEY" -s https://api.nuget.org/v3/index.json
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master